services:
  agentstrace:
    image: "767503528736.dkr.ecr.us-east-2.amazonaws.com/agent/eliza:feature-arm64_fastembed"
    container_name: agent-docker-trace.service
    entrypoint: /opt/agent/docker-entrypoint-strace2.sh
    ports:
      - "3001:3000"
    volumes:
      - tokenizer:/app/node_modules/@anush008/tokenizers/
      - tokenizer:/app/node_modules/fastembed/node_modules/.pnpm/@anush008
      - /opt/agent:/opt/agent
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tee:/app/packages/client-twitter/src/tweetcache
      - akash-plugin-data:/app/packages/plugin-akash/src/
      - tee:/app/db.sqlite
    env_file:
    - /var/run/agent/secrets/env
    - /var/run/agent/secrets/settings
    restart: unless-stopped

  tokenizer:
    image: "767503528736.dkr.ecr.us-east-2.amazonaws.com/nodemodules/tokenizer:latest"
    volumes:
    - tokenizer:/node_modules/tokenizers/

volumes:
  tokenizer: # npm nodemodules/tokenizer:latest
  tee:
  akash-plugin-data:
